version: 2

models:
  - name: fct_summary
    columns:
      - name: customer_id
        description: The customer identification
        tests:
          - unique
          - not_null
      - name: total_amount
        description: The total sum of order amounts