dbt_lakehouse:
  outputs:
    dev:
      #connect_timeout: 10
      host: spark-thrift-server
      method: thrift
      port: 10000
      schema: default
      threads: 1
      thrift_transport: binary
      type: spark
      #user: dbt
  target: dev
